apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-app
  labels:
    app: client-app
    environment: test
spec:
  replicas: 4
  selector:
    matchLabels:
      environment: test
      app: client-app
  template:
    metadata:
      labels:
        environment: test
        app: client-app
    spec:
      containers:
        - name: client-app
          image: gcr.io/{{GCLOUD_PROJECT_ID}}/spring-consul-discovery-demo-client:{{IMAGE_VERSION}}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 120
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "deployment"

---

apiVersion: v1
kind: Service
metadata:
  name: client-app
  labels:
    run: client-app
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: client-app
    environment: test
