spring:
  application.name: client
  cloud:
    consul:
      enabled: false
      host: consul-consul-server
      discovery:
        prefer-ip-address: true
        instanceId: ${spring.application.name}:${random.value}
        serviceName: ${spring.application.name}
        healthCheckPath: ${management.server.servlet.context-path}/health
        healthCheckInterval: 15s

---

spring:
  config.activate.on-profile: deployment
  cloud.consul.enabled: true