spring:
  application.name: client
  cloud:
    consul:
      enabled: false
      discovery:
        prefer-ip-address: true
        instanceId: ${spring.application.name}:${spring.application.instance_id}:${random.value}

---

spring:
  config.activate.on-profile: deployment
  cloud.consul.enabled: true